appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: I3XNt6m05z/LH6uU08GZ/UMMI0zCgIwtCMzs4vrjHha9cq02+PE3gxhe5akdrwFAr7xDWx5RfYGrmCkjm3XSF+ahZNwP5VOtBCtC8Eb9fcYZVIM1EYL2keMpgGLdpVXJOlRhGS9Gkoj+uayWZx0PsgLMdUXEgucDhPoq5r72JxSO5RgzsaCvQM8Rge5cj0RADpmSc8ziAoriWA85XL5egM9RqW5Yrp0Ooz2s++n/Nl6lYcaz9BYlxKRYP32mBsdAh7gGcHDURMujEhXiNViAjvbOgSBiDsKRtnsiJ0kqL5/ZJraipWWg52EEHRbMWNOr9n8KhaTVcAoifcdE3So1iieBN7oQoW2dehWUmqMglOVVck0oAM2LB0a2oXHMHz7wgYTGfyRJoQiWFXgatcJR5m0KcGBpbShfLSVxzb7UVD0Hqmle/iotmovhg1obx5qJVEXlyuQME/3wOJ7S4KMTvJGnS/MF9j7E2cJ7rGmmGOa4+oYS3lKzrbxKojlVtndA2RcSSKhuk0U2fE/5Pf1Qws2txB57DB6WQIqOnRrZ37hbri+6I72JWpfSsrzol/WLPIQnwWFy9OqhYYpv4SKUETgBINt4jGsjsIkfUZqggUllYRrgVzfkznZ0HNLoN/qquE9JvdKb8niiN3JqFjSgBmq/ME9aOzI6qZzr2Lx3/A4=}
